version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/botbuilder.db
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8000}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - botbuilder-network

  # Optional: Qdrant for RAG
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - botbuilder-network

  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - botbuilder-network
    command: redis-server --appendonly yes

networks:
  botbuilder-network:
    driver: bridge

volumes:
  qdrant_data:
  redis_data:
